run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Suggest code simplifications
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused code
    - gofmt         # Check if code is gofmt-ed
    - goimports     # Check import ordering
    - misspell      # Detect misspelled English words
    - revive        # Fast, configurable linter
    - stylecheck    # Replacement for golint
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters
    - gocritic      # Comprehensive linter
    - gosec         # Security checks
    - bodyclose     # Check HTTP response body closed
    - prealloc      # Find slice declarations with pre-allocation

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true
    enable-all: true

  gofmt:
    simplify: true

  misspell:
    locale: US

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else

  gosec:
    excludes:
      - G104 # Allow unhandled errors in deferred calls
      - G304 # Allow file paths from variables (needed for config)

issues:
  exclude-rules:
    # Exclude some linters from running on test files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

  max-issues-per-linter: 0
  max-same-issues: 0
